<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- LINKS -->
    
    <!--Se incluyen los archivos xacro-->
    <xacro:include filename="base.xacro"/>
    <xacro:include filename="wheel.xacro"/>
    <xacro:include filename="steering.xacro"/>
    <xacro:include filename="params.xacro"/>
    <!--Se agrega la base del robot-->
    <xacro:base name="base_link" m="${base_mass}" w="${base_width}" l="${base_length}" h="${base_height}" zoff = "${zoff}"/>
    <!--Voltantes del robot-->
    <xacro:steering name="right_wheel_turn" m="${steering_mass}" rad="${steering_radius}" leng="${steering_length}"/>
    <xacro:steering name="left_wheel_turn"  m="${steering_mass}" rad="${steering_radius}" leng="${steering_length}"/>
    <xacro:steering name="steering_wheel"   m="${steering_mass}" rad="${steering_radius}" leng="${steering_length}"/>
    <!--Ruedas del robot-->
    <xacro:wheel name="left_wheel_rear"     m="${wheel_mass}" rad="${wheel_radius}" leng="${wheel_width}"/>
    <xacro:wheel name="right_wheel_rear"    m="${wheel_mass}" rad="${wheel_radius}" leng="${wheel_width}"/>
    <xacro:wheel name="left_wheel_front"    m="${wheel_mass}" rad="${wheel_radius}" leng="${wheel_width}"/>
    <xacro:wheel name="right_wheel_front"   m="${wheel_mass}" rad="${wheel_radius}" leng="${wheel_width}"/>
    
    <!-- JOINTS -->
    
    <!--Enlace entre sistema de giro con rueda derecha superior-->
    <joint name="front_right_steer_joint" type="revolute">
        <origin xyz="${(base_length/2.5)} ${-(base_width/2 + wheel_width/2)} ${wheel_radius*2 + steering_length/2}" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel_turn"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${lower_limit}" upper="${upper_limit}" effort="100" velocity="0.5"/>
    </joint>
    <!--Enlace entre sistema de giro con rueda izquierda superior-->
    <joint name="front_left_steer_joint" type="revolute">
        <origin xyz="${(base_length/2.5)} ${(base_width/2 + wheel_width/2)} ${wheel_radius*2 + steering_length/2}" rpy="0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel_turn"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${lower_limit}" upper="${upper_limit}" effort="100" velocity="0.5"/>
    </joint>
    <!--Enlace para el volante de direcciÃ³n-->
    <joint name="steering_joint" type="continuous">
        <origin xyz="${(base_length/2.5)} 0.0 ${wheel_radius*2 + steering_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="steering_wheel"/>
        <axis xyz="0 0 1"/>
    </joint>
    <!--Enlace entre rueda izquierda frontal y sistema de giro-->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="right_wheel_turn"/>
        <child link="right_wheel_front"/>
        <origin xyz="0.0 0.0 ${-wheel_radius- steering_length/2}" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1 0.0"/>
    </joint>  
    <!--Enlace entre rueda derecha frontal y sistema de giro-->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="left_wheel_turn"/>
        <child link="left_wheel_front"/>
        <origin xyz="0.0 0.0 ${-wheel_radius - steering_length/2}" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1 0.0"/>
    </joint> 
    <!--Enlace entre rueda izquierda inferior y base-->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_rear"/>
        <origin xyz="${-(base_length/2.5)} ${(base_width/2 + wheel_width/2)} ${wheel_radius}" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>  
    <!--Enlace entre rueda izquierda inferior y base-->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_rear"/>
        <origin xyz="${-(base_length/2.5)} ${-(base_width/2 + wheel_width/2)} ${wheel_radius}" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- PLUGIN GAZENO ACKERMAN ROBOT -->

    <gazebo>
        <plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">

            <update_rate>400.0</update_rate>

            <!-- wheels -->
            <front_left_joint>front_left_wheel_joint</front_left_joint>
            <front_right_joint>front_right_wheel_joint</front_right_joint>
            <rear_left_joint>rear_left_wheel_joint</rear_left_joint>
            <rear_right_joint>rear_right_wheel_joint</rear_right_joint>
            <left_steering_joint>front_left_steer_joint</left_steering_joint>
            <right_steering_joint>front_right_steer_joint</right_steering_joint>
            <steering_wheel_joint>steering_joint</steering_wheel_joint>

            <!-- Max absolute steer angle for tyre in radians-->
            <!-- Any cmd_vel angular z greater than this would be capped -->
            <max_steer>0.6458</max_steer>

            <!-- Max absolute steering angle of steering wheel -->
            <max_steering_angle>7.85</max_steering_angle>

            <!-- Max absolute linear speed in m/s -->
            <max_speed>20</max_speed>

            <!-- PID tuning -->
            <left_steering_pid_gain>100 0.01 0.1</left_steering_pid_gain>
            <right_steering_pid_gain>100 0.01 0.1</right_steering_pid_gain>
            <linear_velocity_pid_gain>50 0.01 0.1</linear_velocity_pid_gain>
            
            <left_steering_i_range>-0.05 0.05</left_steering_i_range>
            <right_steering_i_range>-0.05 0.05</right_steering_i_range>
            <linear_velocity_i_range>-0.05 0.05</linear_velocity_i_range>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <publish_distance>true</publish_distance>

            <odometry_frame>odom_demo</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

        </plugin>
    </gazebo>
</robot>